name: Deploy MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # 1. Checkout repository
      # -----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------
      # 2. Configure AWS credentials
      # -----------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # -----------------------------
      # 3. Package training code
      # -----------------------------
      - name: Package training code
        run: |
          # Only training code goes in tarball
          tar -czvf source_dir.tar.gz train.py
          ls -lh

      # -----------------------------
      # 4. Upload tarball to S3
      # -----------------------------
      - name: Upload training tarball to S3
        run: |
          aws s3 cp source_dir.tar.gz \
            s3://mlops-creditcard-sagemaker/prod_codes/source_dir.tar.gz

      # -----------------------------
      # 5. Upload register_model.py and championselection.py to S3
      # -----------------------------
      - name: Upload MLflow and champion code to S3
        run: |
          aws s3 cp register_model.py \
            s3://mlops-creditcard-sagemaker/prod_codes/register_model.py
          aws s3 cp championselection.py \
            s3://mlops-creditcard-sagemaker/prod_codes/championselection.py

      # -----------------------------
      # 6. Trigger SageMaker Pipeline
      # -----------------------------
      - name: Trigger SageMaker Pipeline
        run: |
          aws sagemaker start-pipeline-execution \
            --pipeline-name CreditCardTrainingPipeline
